# Generated by Django 5.2 on 2025-04-16 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='type',
        ),
    ]
