# Generated by Django 5.2 on 2025-04-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photofile',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
