# Generated by Django 5.2 on 2025-04-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_photo_photo_code_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='photofile',
            index=models.Index(fields=['photo'], name='file_photo_idx'),
        ),
    ]
