# Generated by Django 5.2 on 2025-04-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_photo_status_photofile_file_photo_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='photofile',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
